branch-defaults:
  gsoc18-code:
    environment: systers-mentorship-test
    group_suffix: null
  develop:
    environment: systers-mentorship-dev
    group_suffix: null
  master:
    environment: systers-mentorship
    group_suffix: null
environment-defaults:
  systers-mentorship-test:
    branch: null
    repository: null
global:
  application_name: systers-mentorship
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
